### PR TITLE
Updating flattened field definitions

### PR DESCRIPTION
**Pull request by annecremin**
Updating flattened field definitions plus a tiny tweak to the homepage (teams)

### CODE REVIEW

**Review by Nyzl — APPROVED** [review]
👍 
> [!NOTE]
> this is a great update

**Comment by annecremin** [comment]
Wow how do you do the note?

**Comment by Nyzl** [comment]
`> [!NOTE]`
`> this is a great update`

**Comment by annecremin** [comment]
very cool

**Pull request merged**
